In [8]:
# import pandas as pd
import numpy as np
import pandas as pd
# Đường dẫn đến tệp dữ liệu trên Kaggle
file_path = '/kaggle/input/vindr-mammo-dataset/breast-level_annotations.csv'
pairs = []


# Load 100 mẫu đầu tiên từ tệp CSV vào một DataFrame
df = pd.read_csv(file_path).head(5000)

df.loc[df['breast_birads'] == 'BI-RADS 1', 'breast_birads'] = '1'
df.loc[df['breast_birads'] == 'BI-RADS 2', 'breast_birads'] = '2'
df.loc[df['breast_birads'] == 'BI-RADS 3', 'breast_birads'] = '3'
df.loc[df['breast_birads'] == 'BI-RADS 4', 'breast_birads'] = '4'
df.loc[df['breast_birads'] == 'BI-RADS 5', 'breast_birads'] = '5'

df_new = df[['image_id', 'breast_birads']].copy()

groups = df_new.groupby('breast_birads')


# Lấy mỗi nhóm một phần tử và kết hợp chúng lại với nhau
result = pd.concat([group.head(10).reset_index(drop=True) for name, group in groups])

new_df = pd.DataFrame(columns=result.columns)
selected_rows_list = []

for i in range(0, 10):
    selected_rows = result.loc[result.index == i]
    selected_rows_list.append(selected_rows)

    # Hiển thị kết quả
new_df = pd.concat(selected_rows_list)

# Print the new DataFrame
print(new_df)



                           image_id breast_birads
0  dd9ce3288c0773e006a294188aadba8e             1
0  d8125545210c08e1b1793a5af6458ee2             2
0  aad38467d1f04cedf300c9c8305a3536             3
0  2b46a6fc2c076cfc187b385f6a6f40e6             4
0  581b0e4d471a5c0adc6888cb038fa722             5
1  57fbdd278af5c8789a02b355c11620d4             1
1  290c658f4e75a3f83ec78a847414297c             2
1  2ccefd9e7701acf52c92275e844f7578             3
1  8338207743a394ab8b56b5b920fc30b6             4
1  29896919b15b2dd978a36b2f68a5ad93             5
2  202d761a6b0f86faaeefc39ee18b1c53             1
2  cd0fc7bc53ac632a11643ac4cc91002a             2
2  39a9809abe1441f60f9fab50679c2a73             3
2  396bea28fd4be11598bc53bf5f2b7460             4
2  5d13674e2ed04208bf232e2eeb468f7a             5
3  acccc1727b61b261844d86aa9de53536             1
3  71638b1e853799f227492bfb08a01491             2
3  6770e08049264165b58c5f5ddcfd5b95             3
3  df4b1cfb384dab76abc34cc4db0f5b30             4


In [4]:
import cv2
import pandas as pd
import os
import torch
from torchvision import transforms

In [12]:
from PIL import Image
from torchvision import transforms

def load_image(image_path):
    # Read the image from the path
    image = cv2.imread(image_path)
    
    # Convert the image from OpenCV's BGR format to RGB
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    
    # Convert the NumPy array to a PIL image
    pil_image = Image.fromarray(image)
    
    # Define the transformation pipeline
    transform = transforms.Compose([
        transforms.Resize((224, 224)),  # Resize the image
        transforms.ToTensor()  # Transform the image to a tensor
    ])
    
    # Apply the transformations to the image
    image_tensor = transform(pil_image)
    
    return image_tensor



# Thư mục chứa ảnh
image_folder = "/kaggle/input/vindr-mammo-dataset/Processed_Images"

# Đọc DataFrame từ file CSV
df = new_df
print(df)

# Tạo một cột mới trong DataFrame để lưu tensor của ảnh
df['image_tensor'] = None

# Hàm đệ quy để tìm ảnh trong tất cả các thư mục con
def find_images(image_id, folder):
    for root, dirs, files in os.walk(folder):
        for file in files:
            if file == image_id+'.png':
                image_paths=os.path.join(root, file)
    return image_paths



                           image_id breast_birads image_tensor
0  dd9ce3288c0773e006a294188aadba8e             1         None
0  d8125545210c08e1b1793a5af6458ee2             2         None
0  aad38467d1f04cedf300c9c8305a3536             3         None
0  2b46a6fc2c076cfc187b385f6a6f40e6             4         None
0  581b0e4d471a5c0adc6888cb038fa722             5         None
1  57fbdd278af5c8789a02b355c11620d4             1         None
1  290c658f4e75a3f83ec78a847414297c             2         None
1  2ccefd9e7701acf52c92275e844f7578             3         None
1  8338207743a394ab8b56b5b920fc30b6             4         None
1  29896919b15b2dd978a36b2f68a5ad93             5         None
2  202d761a6b0f86faaeefc39ee18b1c53             1         None
2  cd0fc7bc53ac632a11643ac4cc91002a             2         None
2  39a9809abe1441f60f9fab50679c2a73             3         None
2  396bea28fd4be11598bc53bf5f2b7460             4         None
2  5d13674e2ed04208bf232e2eeb468f7a             5      

In [13]:

image_paths=[]
for index, row in df.iterrows():
    image_id = row['image_id']
    paths = find_images(image_id, image_folder)
    print(paths)
    image_paths.append(paths)
    image_tensor = load_image(paths)
    print(image_tensor.shape)
    #df['image_tensor'] = image_tensor

   


/kaggle/input/vindr-mammo-dataset/Processed_Images/8269f5971eaca3e5d3772d1796e6bd7a/dd9ce3288c0773e006a294188aadba8e.png
torch.Size([3, 224, 224])
/kaggle/input/vindr-mammo-dataset/Processed_Images/b8d273e8601f348d3664778dae0e7e0b/d8125545210c08e1b1793a5af6458ee2.png
torch.Size([3, 224, 224])
/kaggle/input/vindr-mammo-dataset/Processed_Images/cca141f804a8ab8b584d63102bc7f3f7/aad38467d1f04cedf300c9c8305a3536.png
torch.Size([3, 224, 224])
/kaggle/input/vindr-mammo-dataset/Processed_Images/9ec3039bf215173edf48a8b4f23ad56a/2b46a6fc2c076cfc187b385f6a6f40e6.png
torch.Size([3, 224, 224])
/kaggle/input/vindr-mammo-dataset/Processed_Images/10200894bf6f74b2ae92a0cecd37c60c/581b0e4d471a5c0adc6888cb038fa722.png
torch.Size([3, 224, 224])
/kaggle/input/vindr-mammo-dataset/Processed_Images/8269f5971eaca3e5d3772d1796e6bd7a/57fbdd278af5c8789a02b355c11620d4.png
torch.Size([3, 224, 224])
/kaggle/input/vindr-mammo-dataset/Processed_Images/b8d273e8601f348d3664778dae0e7e0b/290c658f4e75a3f83ec78a847414297c.p

In [ ]:
print(image_paths)

In [16]:
pip install vit-pytorch


Note: you may need to restart the kernel to use updated packages.


In [15]:
pip install timm

Note: you may need to restart the kernel to use updated packages.


In [17]:
import torch
from torchvision.models import resnet50, resnet152, densenet121
from vit_pytorch import ViT
import timm
import torch

def load_model(model_type, checkpoint_path):
    if model_type == 'resnet50':
        model = resnet50(pretrained=True)
        num_ftrs = model.fc.in_features
        model.fc = torch.nn.Linear(num_ftrs, 512)
    elif model_type == 'resnet152':
        model = resnet152(pretrained=False)
    elif model_type == 'densenet121':
        model = densenet121(pretrained=True)
        num_classes = 512
        model.classifier = torch.nn.Linear(model.classifier.in_features, num_classes)
    elif model_type == 'vit':
        model_name = 'vit_base_patch16_224'  # Specify the model name
        num_classes = 512  # Number of output classes (adjust as needed)
        model = timm.create_model(model_name, pretrained=False, num_classes=num_classes)

    else:
        raise ValueError(f"Loại mô hình '{model_type}' không được hỗ trợ.")
    
    # Load checkpoint
    checkpoint = torch.load(checkpoint_path, map_location=torch.device('cpu'))
    
    # Extract the model state dictionary from the checkpoint
    if 'model_state_dict' in checkpoint:
        state_dict = checkpoint['model_state_dict']
    else:
        state_dict = checkpoint  # Assuming the entire checkpoint is the state_dict
    
    # Adjust state dictionary keys if necessary
    new_state_dict = {k.replace('model.', ''): v for k, v in state_dict.items()}
    model.load_state_dict(new_state_dict)
    return model
    
    # Load the state


In [69]:
checkpoint='/kaggle/input/ver1-checkpoint/version 1/weights_setting2/densenet121BasedModel/best.pt'
model=load_model('densenet121',checkpoint)


In [56]:
def rank_columns(matrix):
    num_rows, num_cols = matrix.shape
    rank_matrix = torch.zeros(matrix.shape, dtype=torch.int32)

    for col in range(num_cols):
        # Get the values in the column
        column_values = matrix[:, col]
        # Sort the values and get the indices of the sorted values
        sorted_indices = torch.argsort(column_values, descending=True)
        # Assign ranks based on the sorted indices
        for rank, idx in enumerate(sorted_indices):
            rank_matrix[idx, col] = rank + 1  # Rank starts from 1

    return rank_matrix


# Get the rank matrix
matrix=[[0,-2,3],[2,0,1],[3,4,0]]
smatrix = torch.tensor(matrix, dtype=torch.float32)
rank_matrix = rank_columns(smatrix)
print(rank_matrix)

tensor([[3, 3, 1],
        [2, 2, 2],
        [1, 1, 3]], dtype=torch.int32)


In [57]:
import numpy as np
import torch.nn.functional as F

def save_matrix(df,model):
    n = 5
    matrix_root = np.zeros((n, n)) 
    matrix_root_tensor = torch.tensor(matrix_root)
    for i in range(0, 10):
        output = []
        matrix = np.zeros((n, n))  
        selected_rows = result.loc[result.index == i]
        for index, row in selected_rows.iterrows():
            image_id = row['image_id']
            paths = find_images(image_id, image_folder)
            print(image_id,row['breast_birads'])
            input_tensor = load_image(paths)
            input_batch = input_tensor.unsqueeze(0)

            if torch.cuda.is_available():
                input_batch = input_batch.to('cuda')
                model.to('cuda')

            with torch.no_grad():
                out = model(input_batch)
                output.append(out)
        for i in range(0, 5):
            for j in range(0, 5):
                if i == j:
                    matrix[i, j]=1
                else:
                    matrix[i, j] = F.cosine_similarity(output[i], output[j], dim=1)
                    matrix[j, i] = matrix[i, j]  # Since it's symmetric, fill the corresponding element
        matrix = torch.tensor(matrix, dtype=torch.float32)
        print(matrix)
        rank_matrix = rank_columns(matrix)
        print(rank_matrix)
        matrix_root_tensor=matrix_root_tensor+rank_matrix
        
        
        
    return matrix_root_tensor


In [70]:
matrix=save_matrix(df,model)

dd9ce3288c0773e006a294188aadba8e 1
d8125545210c08e1b1793a5af6458ee2 2
aad38467d1f04cedf300c9c8305a3536 3
2b46a6fc2c076cfc187b385f6a6f40e6 4
581b0e4d471a5c0adc6888cb038fa722 5
tensor([[1.0000, 0.7642, 0.6576, 0.7100, 0.7570],
        [0.7642, 1.0000, 0.6920, 0.6916, 0.7227],
        [0.6576, 0.6920, 1.0000, 0.6266, 0.6231],
        [0.7100, 0.6916, 0.6266, 1.0000, 0.7027],
        [0.7570, 0.7227, 0.6231, 0.7027, 1.0000]])
tensor([[1, 2, 3, 2, 2],
        [2, 1, 2, 4, 3],
        [5, 4, 1, 5, 5],
        [4, 5, 4, 1, 4],
        [3, 3, 5, 3, 1]], dtype=torch.int32)
57fbdd278af5c8789a02b355c11620d4 1
290c658f4e75a3f83ec78a847414297c 2
2ccefd9e7701acf52c92275e844f7578 3
8338207743a394ab8b56b5b920fc30b6 4
29896919b15b2dd978a36b2f68a5ad93 5
tensor([[1.0000, 0.7253, 0.7053, 0.6691, 0.6655],
        [0.7253, 1.0000, 0.6918, 0.6797, 0.6565],
        [0.7053, 0.6918, 1.0000, 0.6774, 0.6580],
        [0.6691, 0.6797, 0.6774, 1.0000, 0.6367],
        [0.6655, 0.6565, 0.6580, 0.6367, 1.0000]])
ten

In [71]:
print(matrix/10)
#weights_setting2/densenetBasedModel/best.pt


tensor([[1.0000, 3.6000, 3.4000, 3.8000, 3.4000],
        [3.6000, 1.0000, 3.7000, 3.9000, 3.5000],
        [3.5000, 3.4000, 1.0000, 3.0000, 3.3000],
        [3.9000, 4.0000, 3.7000, 1.0000, 3.8000],
        [3.0000, 3.0000, 3.2000, 3.3000, 1.0000]], dtype=torch.float64)
